### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by MariusVanDerWijden** [google/gofuzz#48]
Hey, I'm trying to use gofuzz with go-fuzz and it is very difficult, because there is no release yet that has the `fuzz.NewFromGoFuzz` feature. I think it may be time to create a new release...

**Comment by lavalamp** [comment]
Yes, you're totally right, let me remember how to push the button...

**Comment by lavalamp** [comment]
https://github.com/google/gofuzz/tree/v1.2.0
