### ISSUE TITLE
Idea: define an interface which types can implement to fuzz themselves

### ISSUE THREAD

**Issue by thockin** [google/gofuzz#9]
That way I can implement constrained types that fuzz properly within bounds (e.g. an IP address string field).

**Comment by lavalamp** [comment]
This sounds tempting, but consider the case where you want two different fuzzes-- one to test your system with data that passes validation checks and one that doesn't. Both seem valuable. ...I guess you could just have the external function "win" if both exist.

**Comment by thockin** [comment]
That's exactly what I implemented.  Site-defined > self-defined >
default-defined > primitives

**Comment by lavalamp** [comment]
Yeah, I hadn't seen your PR when I wrote that. :) Thanks for the change!
